CREATE DATABASE CUSTOSEFINANCAS
	CREATE TABLE USUARIO(
		NOME VARCHAR(50) NOT NULL,
		SOBRENOME VARCHAR(50) NOT NULL, 
		EMAIL VARCHAR(100) NOT NULL,
		CPF VARCHAR(50) NOT NULL,
 		LOGIN VARCHAR(50) NOT NULL,
		SENHA VARCHAR(50) NOT NULL,
		ID INT AUTO_INCREMENT NOT NULL, 


		CONSTRAINT ID_PK PRIMARY KEY (ID));

	CREATE TABLE SERVICO(
		VALOR VARCHAR(50) NOT NULL,
		PRAZO VARCHAR(50) NOT NULL,
		SERV VARCHAR(50) NOT NULL,
		ID_SERV INT AUTO_INCREMENT NOT NULL,
		US_SERV_ID INT NOT NULL,


		CONSTRAINT ID_SERV_PK PRIMARY KEY (ID_SERV)
		CONSTRAINT US_SERV_FK FOREIGN KEY SERVICO(US_SERV_ID) REFERENCES USUARIO(ID));