CREATE database FINANCASeCUSTOS;
	CREATE TABLE USUARIO(
		NOME VARCHAR(50) NOT NULL,
		SOBRENOME VARCHAR(50) NOT NULL,
		TELEFONE VARCHAR(50) NOT NULL,
		CPF VARCHAR(50) NOT NULL,
		EMAIL VARCHAR(50) NOT NULL,
		SENHA VARCHAR(50)NOT NULL,
		ID INT  AUTO_INCREMENT NOT NULL,

		CONSTRAINT ID_PK PRIMARY KEY (ID));

	CREATE TABLE SERVICO(
		SERVICO VARCHAR(50) NOT NULL,
		PRECO VARCHAR(50) NOT NULL,
		PRAZO VARCHAR(50) NOT NULL,
		ID INT AUTO_INCREMENT NOT NULL,
		CONSTRAINT ID_PK PRIMARY KEY (ID));
